### Crear un producto
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "name": "Laptop Dell",
  "sku": "sku-001",
  "price": 1200.0,
  "stock": 10
}

###

### Listar productos
GET http://localhost:8080/api/v1/products
Accept: application/json

###

### Crear inventario (opcional, si API lo expone)
POST http://localhost:8080/api/v1/inventory
Content-Type: application/json

{
  "storeId": "store-1",
  "productId": "sku-001",
  "stock": 5
}

###

### Reservar producto
POST http://localhost:8080/api/v1/inventory/reserve
Content-Type: application/json

{
  "storeId": "store-1",
  "productId": "sku-001",
  "quantity": 2
}

###

### Verificar health
GET http://localhost:8080/actuator/health

###

### Ver métricas Prometheus
GET http://localhost:8080/actuator/prometheus
